---
abstract: 'RESTful read-write RDF repository'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.02'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: WWW::DataWiki
name: WWW-DataWiki
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  WWW::DataWiki:
    file: lib/WWW/DataWiki.pm
  WWW::DataWiki::Controller:
    file: lib/WWW/DataWiki/Controller.pm
  WWW::DataWiki::Controller::Container:
    file: lib/WWW/DataWiki/Controller/Container.pm
  WWW::DataWiki::Controller::Page:
    file: lib/WWW/DataWiki/Controller/Page.pm
  WWW::DataWiki::Controller::Query:
    file: lib/WWW/DataWiki/Controller/Query.pm
  WWW::DataWiki::Controller::Root:
    file: lib/WWW/DataWiki/Controller/Root.pm
  WWW::DataWiki::ErrorHandler::Standard:
    file: lib/WWW/DataWiki/ErrorHandler/Standard.pm
  WWW::DataWiki::Exception:
    file: lib/WWW/DataWiki/Exception.pm
  WWW::DataWiki::Model::Wiki:
    file: lib/WWW/DataWiki/Model/Wiki.pm
  WWW::DataWiki::Resource:
    file: lib/WWW/DataWiki/Resource.pm
  WWW::DataWiki::Resource::Container:
    file: lib/WWW/DataWiki/Resource/Container.pm
  WWW::DataWiki::Resource::Information:
    file: lib/WWW/DataWiki/Resource/Information.pm
  WWW::DataWiki::Resource::Page:
    file: lib/WWW/DataWiki/Resource/Page.pm
  WWW::DataWiki::Resource::ResultBindings:
    file: lib/WWW/DataWiki/Resource/ResultBindings.pm
  WWW::DataWiki::Resource::ResultGraph:
    file: lib/WWW/DataWiki/Resource/ResultGraph.pm
  WWW::DataWiki::Resource::Version:
    file: lib/WWW/DataWiki/Resource/Version.pm
  WWW::DataWiki::Trait::LastModified:
    file: lib/WWW/DataWiki/Trait/LastModified.pm
  WWW::DataWiki::Trait::Negotiator:
    file: lib/WWW/DataWiki/Trait/Negotiator.pm
  WWW::DataWiki::Trait::QueryResult:
    file: lib/WWW/DataWiki/Trait/QueryResult.pm
  WWW::DataWiki::Trait::RdfModel:
    file: lib/WWW/DataWiki/Trait/RdfModel.pm
  WWW::DataWiki::Trait::ResultSet:
    file: lib/WWW/DataWiki/Trait/ResultSet.pm
  WWW::DataWiki::Trait::Textual:
    file: lib/WWW/DataWiki/Trait/Textual.pm
  WWW::DataWiki::Trait::Title:
    file: lib/WWW/DataWiki/Trait/Title.pm
  WWW::DataWiki::Utils:
    file: lib/WWW/DataWiki/Utils.pm
  WWW::DataWiki::View::General:
    file: lib/WWW/DataWiki/View/General.pm
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Plugin::Cache::HTTP: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::ErrorCatcher: 0
  Catalyst::Plugin::StackTrace: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: 5.90006
  CatalystX::RoleApplicator: 0
  CatalystX::Syntax::Action: 0
  CatalystX::TraitFor::Dispatcher::ExactMatch: 0
  Config::General: 0
  Data::Dumper: 0
  Data::UUID: 0
  DateTime: 0
  DateTime::Format::HTTP: 0
  DateTime::Format::Strptime: 0
  DateTimeX::Format::Ago: 0
  Digest::MD5: 0
  File::Slurp: 0
  File::Spec: 0
  HTML::HTML5::Builder: 0
  HTML::HTML5::Writer: 0
  HTTP::Headers: 0
  HTTP::Negotiate: 0
  IO::Compress::Gzip: 0
  LWP::UserAgent: 0
  Moose: 0
  MooseX::Declare: 0
  PerlIO::gzip: 0
  RDF::QueryX::Lazy: 0
  RDF::RDFa::Generator::HTML::Pretty: 0
  RDF::RDFa::Parser: 1.096
  RDF::TriN3: 0.135
  RDF::Trine: 0.135
  StackTrace::Auto: 0
  Throwable: 0
  Time::HiRes: 0
  Try::Tiny: 0
  UNIVERSAL::AUTHORITY: 0
  URI::Escape: 0
  XML::Atom::FromOWL: 0
  XML::LibXML::PrettyPrint: 0
  namespace::autoclean: 0
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=WWW-DataWiki
  homepage: https://metacpan.org/release/WWW-DataWiki
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-www-datawiki
version: 0.001
